- name: download day0 config
  hosts: hq_routers
  connection: network_cli
  gather_facts: no
  tasks:
  - name: configurable backup path
    cisco.ios.ios_config:
      backup: yes 
      backup_options:
        dir_path: "{{ lookup('env', 'PWD') }}"
